@echo off
echo Compilando proyecto...
cd /d "d:\CHEEMYS\EPN\SEMESTRE IV\ISR\Proyecto\SGEJ-A\Prj_SGEJ-A\SGEJ-A"

echo Compilando con javac...
javac -cp "D:\CHEEMYS\PATHS\JavaFX\javafx-sdk-24.0.1\lib\*;D:\CHEEMYS\PATHS\sqlite-jdbc-3.45.0.0.jar" -d target/classes src/main/java/application/*.java src/main/java/application/model/*.java src/main/java/application/database/*.java src/main/java/application/dao/*.java src/main/java/application/service/*.java src/main/java/application/controllers/*.java src/main/java/application/controllers/cliente/*.java

echo Copiando recursos...
xcopy /E /Y src\main\resources\* target\classes\

echo Ejecutando SGEJ-A...
java --module-path "D:\CHEEMYS\PATHS\JavaFX\javafx-sdk-24.0.1\lib" --add-modules javafx.controls,javafx.fxml --enable-native-access=javafx.graphics -cp "target/classes;D:\CHEEMYS\PATHS\sqlite-jdbc-3.45.0.0.jar" application.App
pause
